//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingShengReportToBill.UploadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UploadService.posSoap")]
    public interface posSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemMasterInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetItemMasterInfo(string strCallUserCode, string strCallPassword, string strItemCode, string strItemGroup0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemMasterInfoByStore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetItemMasterInfoByStore(string strCallUserCode, string strCallPassword, string strStoreCode, string strItemCode, string strItemGroup0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostSales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode PostSales(string strCallUserCode, string strCallPassword, string strStoreCode, string strType, string strSalesDate_YYYYMMDD, string strSalesTime_HHMISS, string strSalesDocNo, string strVipCode, string strTenderCode, string strRemark, string strItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckCallUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode CheckCallUser(string strCallUserCode, string strCallPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface posSoapChannel : BingShengReportToBill.UploadService.posSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class posSoapClient : System.ServiceModel.ClientBase<BingShengReportToBill.UploadService.posSoap>, BingShengReportToBill.UploadService.posSoap {
        
        public posSoapClient() {
        }
        
        public posSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public posSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public posSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public posSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode GetItemMasterInfo(string strCallUserCode, string strCallPassword, string strItemCode, string strItemGroup0) {
            return base.Channel.GetItemMasterInfo(strCallUserCode, strCallPassword, strItemCode, strItemGroup0);
        }
        
        public System.Xml.XmlNode GetItemMasterInfoByStore(string strCallUserCode, string strCallPassword, string strStoreCode, string strItemCode, string strItemGroup0) {
            return base.Channel.GetItemMasterInfoByStore(strCallUserCode, strCallPassword, strStoreCode, strItemCode, strItemGroup0);
        }
        
        public System.Xml.XmlNode PostSales(string strCallUserCode, string strCallPassword, string strStoreCode, string strType, string strSalesDate_YYYYMMDD, string strSalesTime_HHMISS, string strSalesDocNo, string strVipCode, string strTenderCode, string strRemark, string strItems) {
            return base.Channel.PostSales(strCallUserCode, strCallPassword, strStoreCode, strType, strSalesDate_YYYYMMDD, strSalesTime_HHMISS, strSalesDocNo, strVipCode, strTenderCode, strRemark, strItems);
        }
        
        public System.Xml.XmlNode CheckCallUser(string strCallUserCode, string strCallPassword) {
            return base.Channel.CheckCallUser(strCallUserCode, strCallPassword);
        }
    }
}
