// <auto-generated />
namespace Wing.ABPMetroWPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modify_user_20180226 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modify_user_20180226));
        
        string IMigrationMetadata.Id
        {
            get { return "201802261533247_modify_user_20180226"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
